apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: e-commerce-365907
  artifacts:
  - image: us.gcr.io/e-commerce-365907/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/.ts'
  - image: us.gcr.io/e-commerce-365907/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: '**/*/.tsx'
  - image: us.gcr.io/e-commerce-365907/cart
    context: cart
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: '**/*/.ts'
  - image: us.gcr.io/e-commerce-365907/mail
    context: mail
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: '**/*/.ts'
  - image: us.gcr.io/e-commerce-365907/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: '**/*/.ts'
  - image: us.gcr.io/e-commerce-365907/favorites
    context: favorites
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: '**/*/.ts'


