apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: e-commerce.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-srv
            port:
              number: 3000
      - path: /api/users/
        pathType: Prefix
        backend:
          service:
            name: auth-srv
            port:
              number: 4000
      - path: /api/cart/
        pathType: Prefix
        backend:
          service:
            name: cart-srv
            port:
              number: 4001
      - path: /api/mail/
        pathType: Prefix
        backend:
          service:
            name: mail-srv
            port:
              number: 4002
      - path: /api/favorites/
        pathType: Prefix
        backend:
          service:
            name: favorites-srv
            port:
              number: 4003
      - path: /api/payments/
        pathType: Prefix
        backend:
          service:
            name: payments-srv
            port:
              number: 4004


